In [16]:
print('hello world')

hello world


In [17]:
import numpy as np

import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

In [18]:
sentences = [
 "I love this product",
 "This movie made me smile",
 "Service was friendly and quick",
 "Today felt bright and happy",
 "This is the best day",
 "Absolutely fantastic experience",
 "I enjoyed every single moment",
 "Great job, well done",
 "The food tasted delicious",
 "Totally recommend to everyone",
 "Very satisfied with results",
 "This worked better than expected",
 "Amazing quality and value",
 "Such a pleasant surprise",
 "I feel positive about this",
 "I hate this product",
 "This movie bored me",
 "Service was rude and slow",
 "Today was cold and lonely",
 "This is the worst day",
 "Terrible experience overall",
 "I regret buying this",
 "Very disappointed with results",
 "The food tasted awful",
 "Do not recommend this",
 "It broke after one use",
 "Not worth the money",
 "Utterly frustrating and annoying",
 "I feel negative about this",
 "Such a waste of time",
]

sentences


['I love this product',
 'This movie made me smile',
 'Service was friendly and quick',
 'Today felt bright and happy',
 'This is the best day',
 'Absolutely fantastic experience',
 'I enjoyed every single moment',
 'Great job, well done',
 'The food tasted delicious',
 'Totally recommend to everyone',
 'Very satisfied with results',
 'This worked better than expected',
 'Amazing quality and value',
 'Such a pleasant surprise',
 'I feel positive about this',
 'I hate this product',
 'This movie bored me',
 'Service was rude and slow',
 'Today was cold and lonely',
 'This is the worst day',
 'Terrible experience overall',
 'I regret buying this',
 'Very disappointed with results',
 'The food tasted awful',
 'Do not recommend this',
 'It broke after one use',
 'Not worth the money',
 'Utterly frustrating and annoying',
 'I feel negative about this',
 'Such a waste of time']

In [19]:
labels = [1]*15 + [0]*15
labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [20]:
labels = np.array(labels)
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
vocab_size = 2000
tok = Tokenizer(num_words= vocab_size , oov_token = '<OOV>')
tok

In [22]:
tok.fit_on_texts(sentences)
tok

In [23]:
seqs = tok.texts_to_sequences(sentences)
seqs

[[3, 26, 2, 7],
 [2, 8, 27, 9, 28],
 [10, 6, 29, 4, 30],
 [11, 31, 32, 4, 33],
 [2, 12, 5, 34, 13],
 [35, 36, 14],
 [3, 37, 38, 39, 40],
 [41, 42, 43, 44],
 [5, 15, 16, 45],
 [46, 17, 47, 48],
 [18, 49, 19, 20],
 [2, 50, 51, 52, 53],
 [54, 55, 4, 56],
 [21, 22, 57, 58],
 [3, 23, 59, 24, 2],
 [3, 60, 2, 7],
 [2, 8, 61, 9],
 [10, 6, 62, 4, 63],
 [11, 6, 64, 4, 65],
 [2, 12, 5, 66, 13],
 [67, 14, 68],
 [3, 69, 70, 2],
 [18, 71, 19, 20],
 [5, 15, 16, 72],
 [73, 25, 17, 2],
 [74, 75, 76, 77, 78],
 [25, 79, 5, 80],
 [81, 82, 4, 83],
 [3, 23, 84, 24, 2],
 [21, 22, 85, 86, 87]]

In [24]:
max_len = max(len(s) for s in seqs)

X = pad_sequences(seqs , maxlen = max_len , padding = 'post')
y = labels

In [25]:
X

array([[ 3, 26,  2,  7,  0],
       [ 2,  8, 27,  9, 28],
       [10,  6, 29,  4, 30],
       [11, 31, 32,  4, 33],
       [ 2, 12,  5, 34, 13],
       [35, 36, 14,  0,  0],
       [ 3, 37, 38, 39, 40],
       [41, 42, 43, 44,  0],
       [ 5, 15, 16, 45,  0],
       [46, 17, 47, 48,  0],
       [18, 49, 19, 20,  0],
       [ 2, 50, 51, 52, 53],
       [54, 55,  4, 56,  0],
       [21, 22, 57, 58,  0],
       [ 3, 23, 59, 24,  2],
       [ 3, 60,  2,  7,  0],
       [ 2,  8, 61,  9,  0],
       [10,  6, 62,  4, 63],
       [11,  6, 64,  4, 65],
       [ 2, 12,  5, 66, 13],
       [67, 14, 68,  0,  0],
       [ 3, 69, 70,  2,  0],
       [18, 71, 19, 20,  0],
       [ 5, 15, 16, 72,  0],
       [73, 25, 17,  2,  0],
       [74, 75, 76, 77, 78],
       [25, 79,  5, 80,  0],
       [81, 82,  4, 83,  0],
       [ 3, 23, 84, 24,  2],
       [21, 22, 85, 86, 87]], dtype=int32)

In [26]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
X[0]

array([ 3, 26,  2,  7,  0], dtype=int32)

In [28]:
X[29]

array([21, 22, 85, 86, 87], dtype=int32)

In [29]:
Embed_dim = 16
rnn_units = 8


In [30]:
inp = Input(shape=(max_len , ), dtype='int32' , name ='input')
x = Embedding(input_dim=vocab_size , output_dim=Embed_dim , mask_zero=True , name='embed')(inp)


rnn = SimpleRNN(units = rnn_units , return_sequences = False , return_state = False , name = 'simple_rnn')
x_last = rnn(x)
out = Dense(1 , activation='sigmoid' , name='out')(x_last)
model = Model(inputs = inp , outputs = out)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 5)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embed (Embedding)   │ (None, 5, 16)     │     32,000 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_1         │ (None, 5)         │          0 │ input[0][0]       │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ simple_rnn          │ (None, 8)         │        200 │ embed[0][0],      │
│ (SimpleRNN)         │                   │            │ not_equal_1[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ out (Dense)         │ (None, 1)         │          9 │ simple_rnn[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 32,209 (125.82 KB)

 Trainable params: 32,209 (125.82 KB)

 Non-trainable params: 0 (0.00 B)